version: '3.5'

services:
  symfony:
    image: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
      args:
        BUILD_ARGUMENT_ENV: dev
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}
    expose:
      - 80
      - 443
    ports:
      - "8888:80"
      - "443:443"
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - mysql
    networks:
      - symfony

  mysql:
    image: mysql
    container_name: blog_in_symfony_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    volumes:
      - ./var/mysql-data:/var/lib/mysql:delegated
      - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - symfony
networks:
  symfony:
    name: symfony